// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-businesses.ts
import { createClient } from "npm:@supabase/supabase-js@^2.50.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var SUPABASE_URL = "https://pihmoaogjjiicfnkmpbe.supabase.co";
var SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpaG1vYW9namppaWNmbmttcGJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMDU5NTIsImV4cCI6MjA2NDc4MTk1Mn0.AwP8FI4ykefc4CCq-48QF_f1jbK3vTy41STytcQ5SaU";
var search_businesses_default = defineTool({
  name: "search_businesses",
  title: "Search wellness businesses",
  description: "Search GymSpaYoga's public directory of gyms, spas, yoga studios, therapists, and chiropractors. Filter by city and/or business type.",
  inputSchema: {
    city: z.string().optional().describe("City name filter (partial match)."),
    business_type: z.string().optional().describe("One of: gym, spa, yoga, therapist, chiropractor."),
    limit: z.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ city, business_type, limit }) => {
    const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let query = supabase.from("public_business_listings").select(
      "business_name, business_type, city, state, monthly_price, session_price, description, amenities"
    ).limit(limit);
    if (city) query = query.ilike("city", `%${city}%`);
    if (business_type) query = query.eq("business_type", business_type);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { businesses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-trainers.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.50.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var SUPABASE_URL2 = "https://pihmoaogjjiicfnkmpbe.supabase.co";
var SUPABASE_PUBLISHABLE_KEY2 = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpaG1vYW9namppaWNmbmttcGJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMDU5NTIsImV4cCI6MjA2NDc4MTk1Mn0.AwP8FI4ykefc4CCq-48QF_f1jbK3vTy41STytcQ5SaU";
var search_trainers_default = defineTool2({
  name: "search_trainers",
  title: "Search trainers",
  description: "Search GymSpaYoga's public directory of fitness, yoga, and wellness trainers. Filter by location and/or category.",
  inputSchema: {
    location: z2.string().optional().describe("Location/city filter (partial match)."),
    category: z2.string().optional().describe("Trainer category, e.g. yoga, fitness."),
    limit: z2.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ location, category, limit }) => {
    const supabase = createClient2(SUPABASE_URL2, SUPABASE_PUBLISHABLE_KEY2, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let query = supabase.from("public_trainer_listings").select(
      "name, category, location, hourly_rate, specializations, bio, trainer_tier, experience_years"
    ).limit(limit);
    if (location) query = query.ilike("location", `%${location}%`);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { trainers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-blogs.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.50.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var SUPABASE_URL3 = "https://pihmoaogjjiicfnkmpbe.supabase.co";
var SUPABASE_PUBLISHABLE_KEY3 = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpaG1vYW9namppaWNmbmttcGJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMDU5NTIsImV4cCI6MjA2NDc4MTk1Mn0.AwP8FI4ykefc4CCq-48QF_f1jbK3vTy41STytcQ5SaU";
var list_blogs_default = defineTool3({
  name: "list_blogs",
  title: "List wellness blog posts",
  description: "List published GymSpaYoga wellness blog posts. Optionally filter by category or search text in the title.",
  inputSchema: {
    search: z3.string().optional().describe("Text to search in blog titles."),
    category: z3.string().optional().describe("Blog category filter."),
    limit: z3.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ search, category, limit }) => {
    const supabase = createClient3(SUPABASE_URL3, SUPABASE_PUBLISHABLE_KEY3, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let query = supabase.from("blogs").select("id, title, excerpt, category, author_name, published_at, slug").eq("status", "published").order("published_at", { ascending: false }).limit(limit);
    if (search) query = query.ilike("title", `%${search}%`);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { blogs: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "gymspayoga-mcp",
  title: "GymSpaYoga MCP",
  version: "0.1.0",
  instructions: "Tools to search GymSpaYoga's public directory of gyms, spas, yoga studios, trainers, therapists, chiropractors, and wellness blog content across India.",
  tools: [search_businesses_default, search_trainers_default, list_blogs_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
